### ISSUE TITLE
Generated heapdumps have incorrect retained size? (???)

### ISSUE THREAD

**Issue by jwalton** [bnoordhuis/node-heapdump#50] opened 2015-02-04 16:42 UTC
I'll prefix this by saying I suspect this isn't actually node-heapdump at fault, but I was wondering if you had some insight into what is going on here?  :)

If I generate a heap dump from my app (on Linux, using node 0.10.31), then load this dump into Chrome 40.0.2214.94 (64-bit), in the dev tools every single object has a shallow size which is identical to the retained size:

![screen shot 2015-02-04 at 11 38 57 am](https://cloud.githubusercontent.com/assets/1771003/6044619/7093a462-ac62-11e4-8cea-9e1e082764a9.png)

If I go to the "Containment" view, I see:

![screen shot 2015-02-04 at 11 31 24 am](https://cloud.githubusercontent.com/assets/1771003/6044637/981ed13c-ac62-11e4-8999-b6be732b3c81.png)

If I open one of these up, I see the retained size is smaller than the objects inside:

![screen shot 2015-02-04 at 11 31 59 am](https://cloud.githubusercontent.com/assets/1771003/6044651/be09cdf2-ac62-11e4-83b9-e74abdae60db.png)

**Comment by ChALkeR** [comment] 2015-04-12 23:24
I have this issue too.
Example heapdump from a testcase app: http://oserv.org/bugs/node-heapdump/heapdump-194314979.440694.heapsnapshot.xz

Look at Test or Array objects, for example.

**Comment by ChALkeR** [comment] 2015-04-13 00:33
Btw, for me heapsnapshot (not the uploaded testcase one, the real one) had a reported size of 32m and the real memory block rss size of 274m.

**Comment by bnoordhuis** [comment] 2015-04-13 10:14
@jwalton Sorry for the delay, I must have missed the notification email for this issue.

I looked into it and there are at least two issues:

1. v0.10 heap snapshots are is incompatible with recent versions of Chrome Developer Tools.  The latter expects fields that are missing in the output from the former.  I can perhaps add a script that post-processes the .heapsnapshot file.

2. v0.12 and io.js also have self size == retained size, which is odd because they are new enough to produce compatible output (io.js is, anyway.)

It's not a bug in Chrome's .heapsnapshot loader; it works fine when you take an in-browser snapshot and save+load it.

I observe that the postorder index step takes a hell of a long time with snapshots created with node-heapdump compared to in-browser snapshots of roughly the same size.

I'm not sure what to make of that.  node-heapdump takes the data from V8 pretty much as-is and the version of V8 in io.js is almost identical to the one in Chrome 41.

**Comment by ChALkeR** [comment] 2015-05-28 19:39
@vietkute02 mentioned in the IRC chat that a combination of Chrome 37, node-heapdump 0.3.5 (current) and node 0.11.x does not have this bug.

**Comment by bnoordhuis** [comment] 2015-05-28 20:00
> I observe that the postorder index step takes a hell of a long time with snapshots created with node-heapdump compared to in-browser snapshots of roughly the same size.
>
> I'm not sure what to make of that. node-heapdump takes the data from V8 pretty much as-is and the version of V8 in io.js is almost identical to the one in Chrome 41.

I forgot to mention it here but I did eventually figure out what the issue is - or at least, what I believe the issue is - and it's perhaps also responsible for the self_size == retained_size issue.

Heap snapshots from io.js and node.js processes seem to have much deeper and more cyclic object graphs than in-browser ones.  I speculate that DevTools' snapshot loader bails out after it reaches a certain depth but it takes a lot of time and it doesn't figure out what the real retained size is.

**Comment by DeTeam** [comment] 2015-07-13 15:32
@bnoordhuis is there any ticket to watch in node/io/chrome or we'd need to report it?

**Comment by jspavlick** [comment] 2015-09-02 19:37
I will say that by using Chromium 37 downloaded from here - http://sourceforge.net/projects/osxportableapps/files/Chromium/ChromiumOSX_37.0.2062.94.dmg/download?use_mirror=iweb&r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fosxportableapps%2Ffiles%2FChromium%2F&use_mirror=iweb 

I saw self size !== retained size. However, the full size of the heap dump (60MB for me) was still incorrect.

**Comment by ChALkeR** [comment] 2015-09-02 20:18
@jspavlick What's your `rss`/`heapTotal`/`heapUsed`? It looks like that the graphs you posted to #62 measure `rss`, and heapdump measures `headUsed`.

**Comment by jspavlick** [comment] 2015-09-02 20:32
Buffers do *not* have `self_size === retained_size` in Chromium 37. Not sure about rss/heapTotal/heapUsed, I just took a screenshot of whatever New Relic gave me.

**Comment by Zarel** [comment] 2015-12-11 23:53
I'm also having this issue, on iojs 2.3.4 (don't ask).

self size seems correct; it's just retained size that isn't getting calculated.

**Comment by ChuntaoLu** [comment] 2016-02-16 22:22
I was facing the same problem of shallow size == retained size, which is solved by enabling "Show advanced heap snapshot properties" check box in the DevTools settings panel.

**Comment by ChALkeR** [comment] 2016-02-16 22:30
@ChuntaoLu This works for me for my testcase heapdump linked above.

@bnoordhuis The issue could be closed with documenting that «Show advanced heap snapshot properties» should be enabled in Chrome, I suppose.

**Comment by bnoordhuis** [comment] 2017-03-10 09:35
> «Show advanced heap snapshot properties»

@ChALkeR Do you know if that option still exists in Chrome 56?  I can't find it anymore.  FWIW, I haven't received more reports so I suspect this has been fixed upstream.

Refs: https://bugs.chromium.org/p/chromium/issues/detail?id=455374

**Comment by bnoordhuis** [comment] 2017-07-06 15:18
I'm fairly sure this has been fixed in Chromium so I'll go ahead and close this out.

**Closed by bnoordhuis** 2017-07-06 15:18 UTC
