### ISSUE TITLE
Using in Electron

### ISSUE THREAD

**Issue by gdavidkov** [bnoordhuis/node-heapdump#147] opened 2020-09-29 13:15 UTC
Hello,
First, I want to thank you for the great app. 
I wonder if I can use it in Electron.
According to the Electron's [documentation](https://www.electronjs.org/docs/tutorial/using-native-node-modules#a-note-about-win_delay_load_hook), we have to use  win_delay_load_hook.
Can somebody guide me on how to build it with this hook?

Thank you very much!

**Comment by bnoordhuis** [comment] 2020-09-29 13:22
I'm reasonably sure people have used it with electron in the past. What error or errors do you get? Does reverting 78056ec1 make it work?

**Comment by gdavidkov** [comment] 2020-09-29 13:30
I got the same error because I had changed win_delay_load_hook to true. When it is false, I can build it but Electron doesn't start. It throws the following error
![image](https://user-images.githubusercontent.com/5815794/94564673-eebeb380-0270-11eb-940f-efc46d1d5884.png)

**Comment by bnoordhuis** [comment] 2020-09-29 13:49
Right, I remember seeing that error before and I think it was caused by the dynamic linker not being able to resolve the vtable for the `v8::OutputStream` class that node-heapdump uses.

Unfortunately, I don't have good suggestions on how to fix it and I don't have time right now to look into it myself. Let me know when you figure it out and we'll see what we can do to make it work better in the future.

**Comment by jeange1003** [comment] 2022-02-24 09:29
I encountered similar problem and resolved by running
`
electron-rebuild -v [target-electron-version]
`

**Closed** 2022-11-12 09:53 UTC

**Comment by rosendolu** [comment] 2024-06-18 13:07
Used with electron 
```
{
    "node": "18.17.1",
    "chrome": "118.0.5993.120",
    "electron": "27.0.3"
   "heapdump":"0.3.15"
}
```
Tried skip electron-rebuild  
```
Module did not self-register: '\\?\D:\github\app\node_modules\heapdump\build\Release\addon.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
```

rebuild  error 
```
Error: The specified procedure could not be found.
\\?\D:\github\app\node_modules\heapdump\build\Release\addon.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
```

**As a result** 
```
const v8 = requrie("v8")
v8.writeHeapSnapshot(filename)
```
