### ISSUE TITLE
Fails on AWS Elastic Beanstalk with node 8.1.4

### ISSUE THREAD

**Issue by ChrisCinelli** [bnoordhuis/node-heapdump#108] opened 2017-07-18 01:22 UTC
```
-------------------------------------
/var/log/eb-commandprocessor.log
-------------------------------------
  npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the heapdump@0.3.7 install script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /tmp/.npm/_logs/2017-07-18T00_29_41_069Z-debug.log
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v8.1.4-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.
  UTC 2017/07/18 00:29:41 cannot find application npm debug log at /tmp/deployment/application/npm-debug.log 
  
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
      main()
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
      node_version_manager.run_npm_install(options.app_path)
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
      self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
      raise e
  subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v8.1.4-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1 (ElasticBeanstalk::ExternalInvocationError)
caused by: + /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install
  npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
  
  > heapdump@0.3.7 install /tmp/deployment/application/node_modules/heapdump
  > node-gyp rebuild
  
  gyp ERR! configure error 
  gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/heapdump/build'
  gyp ERR! System Linux 4.9.32-15.41.amzn1.x86_64
  gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v8.1.4-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v8.1.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
  gyp ERR! cwd /tmp/deployment/application/node_modules/heapdump
  gyp ERR! node -v v8.1.4
  gyp ERR! node-gyp -v v3.6.2
  gyp ERR! not ok 
```

**Comment by bnoordhuis** [comment] 2017-07-18 06:38
The error is this:

> EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/heapdump/build'

And that's a permissions issue with the environment you are trying to build in.  Can't really help you with that, I'm afraid.

**Comment by ChrisCinelli** [comment] 2017-07-19 21:05
What about this? This is happening locally:

```
Error: Cannot find module '../build/Debug/addon'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/website/node_modules/heapdump/lib/main.js:18:15)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/website/node_modules/babel-watch/runner.js:63:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/website/server/api/dev.js:8:1)
```

**Comment by bnoordhuis** [comment] 2017-07-19 22:44
You probably built the add-on for the wrong arch or node version.  If you use the latest version, you'll get a better error message.

**Comment by Ltty** [comment] 2017-10-18 13:45
Just tried and it fails when I try to deploy it to AWS, locally it's working fine. The thing is: I cannot find any clue in the logs why it can't install:

` > heapdump@0.3.9 install /tmp/deployment/application/node_modules/heapdump
  > node-gyp rebuild
  
  
  
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v7.6.0-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
      main()
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
      node_version_manager.run_npm_install(options.app_path)
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
      self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
      raise e
  subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v7.6.0-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1 (ElasticBeanstalk::ExternalInvocationError)
caused by: + /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install
  npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead
  npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
  
  > heapdump@0.3.9 install /tmp/deployment/application/node_modules/heapdump
  > node-gyp rebuild
  
  
  
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v7.6.0-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
      main()
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
      node_version_manager.run_npm_install(options.app_path)
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
      self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
      raise e
  subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v7.6.0-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1 (Executor::NonZeroExitStatus)`

**Comment by bagel2405** [comment] 2017-10-21 18:52
Hi Ltty,
 Im facing the same issue like yours when trying to depoly to aws, do you have any clue..?

thanks!

**Comment by maksim-amko** [comment] 2018-01-09 09:54
Have a look at this [Beanstalk: Node.js deployment - node-gyp fails due to permission denied
](https://stackoverflow.com/questions/46001516/beanstalk-node-js-deployment-node-gyp-fails-due-to-permission-denied)

The solution is to add the file .npmrc to the application with the content: `unsafe-perm=true`

**Comment by dmkorb** [comment] 2019-05-24 21:16
Thanks @maksim-amko! 

What bugs me is that a handful of deploys worked over a few weeks and this error started out of the blue.
Well, seems fixed with .npmrc.

**Comment by kshitijpurwar** [comment] 2019-06-23 11:01
@maksim-amko Facing the same issue, no solution working so far. I am on `Node 10.16`. 😢  😞 

### Tried 
1. `.npmrc` with `unsafe-perm=true`
2. Changing permission with `.ebextensions`, [more here](https://medium.com/@jharris.sf/npm-rebuild-elastic-beanstalk-and-permissions-be1c6fceba9a)

Taken the AWS developer support plan now as last resort.

**Closed** 2020-07-02 21:02 UTC
